version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:0-3.11
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity
    depends_on:
      - firefox
    links:
      - "firefox:webdriver"

  firefox:
    image: seleniarm/standalone-firefox:latest
    ports:
      - 4444:4444
      - 7900:7900

